# Generated by Django 3.0.2 on 2020-02-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwarsapi', '0003_auto_20200203_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='max_speed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='passengers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_class',
            field=models.CharField(max_length=200),
        ),
    ]
