# Generated by Django 3.0.2 on 2020-02-03 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starwarsapi', '0006_auto_20200203_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starwarsapi.Character')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starwarsapi.Movie')),
            ],
        ),
    ]
