# Generated by Django 3.0.2 on 2020-02-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwarsapi', '0009_auto_20200203_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='quote',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
