# Generated by Django 3.0.2 on 2020-02-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwarsapi', '0020_delete_usercharacter'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, max_length=200)),
                ('planet', models.CharField(blank=True, max_length=200)),
                ('species', models.CharField(blank=True, max_length=200)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('force_sensitive', models.BooleanField(blank=True)),
                ('side', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('best_quote', models.CharField(blank=True, max_length=200)),
                ('lightsaber', models.CharField(blank=True, max_length=200)),
                ('sith_name', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
