# Generated by Django 3.0.2 on 2020-02-05 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starwarsapi', '0021_usercharacter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCharacter',
        ),
    ]
