# Generated by Django 3.0.2 on 2020-02-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwarsapi', '0027_auto_20200207_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwildlife',
            name='diet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
