# Generated by Django 3.0.3 on 2020-02-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwarsapi', '0029_auto_20200209_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwildlife',
            name='category',
            field=models.CharField(default='animal', max_length=200),
        ),
    ]
