# Generated by Django 3.0.2 on 2020-02-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwarsapi', '0007_charactermovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='force_sensitive',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='side',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='opening_crawl',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
