# Generated by Django 3.0.2 on 2020-02-04 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwarsapi', '0010_character_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='lightsaber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
