# Generated by Django 3.0.2 on 2020-02-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwarsapi', '0011_character_lightsaber'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='sith_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
