# Generated by Django 3.0.2 on 2020-02-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwarsapi', '0013_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='roman_numeral',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
