# Generated by Django 3.0.2 on 2020-02-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwarsapi', '0014_movie_roman_numeral'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
