# Generated by Django 3.0.2 on 2020-02-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwarsapi', '0023_usercharacter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCharacter',
        ),
        migrations.AddField(
            model_name='wildlife',
            name='diet',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
