# Generated by Django 3.0.2 on 2020-02-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwarsapi', '0025_usercharacter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplanet',
            name='climate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userplanet',
            name='terrain',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
